//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infraction
    {
        public int Infr_Id { get; set; }
        public string Studentnum { get; set; }
        public string Library { get; set; }
        public string L_inf { get; set; }
        public string Health { get; set; }
        public string H_inf { get; set; }
        public string Osas { get; set; }
        public string O_inf { get; set; }
        public string Registrar { get; set; }
        public string R_inf { get; set; }
    }
}
