//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrationEntities : DbContext
    {
        public RegistrationEntities()
            : base("name=RegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Admin_Acc> Admin_Acc { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Concern> Concerns { get; set; }
        public virtual DbSet<Infraction> Infractions { get; set; }
        public virtual DbSet<LogAct> LogActs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Pass_Reset> Pass_Reset { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<YearLevel> YearLevels { get; set; }
    }
}
