//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetCode
    {
        public int RC_id { get; set; }
        public string Studentnum { get; set; }
        public string Code { get; set; }
        public string Username { get; set; }
        public string Status { get; set; }
    }
}
