//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int S_id { get; set; }
        public string Code { get; set; }
        public string Subject { get; set; }
        public string Unit { get; set; }
        public string Room { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Professor { get; set; }
    }
}
