//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string SubjectCode { get; set; }
        public string Subject1 { get; set; }
        public Nullable<int> IdProfessor { get; set; }
        public string Professor { get; set; }
    }
}
